// ─────────────────────────────────────────────────────────────────
// lib/distribution/quality.ts
// Pre-publish quality scoring. The autopilot will NOT publish a bundle
// that fails this gate (e.g. mock output, too-short article, missing
// FAQ/SEO) — protecting the index from thin/placeholder pages.
// Deterministic, no AI.
// ─────────────────────────────────────────────────────────────────

import type { ContentBundle, Locale } from './types'

export interface QualityScore {
  score: number          // 0..100
  pass: boolean
  issues: string[]
}

const THRESHOLD = Number(process.env.QUALITY_THRESHOLD) || 60

export function scoreBundleQuality(bundle: ContentBundle): QualityScore {
  const issues: string[] = []
  let score = 100

  if (!bundle.live) { score -= 50; issues.push('generated by mock provider (not live AI)') }

  const locales = Object.keys(bundle.locales) as Locale[]
  for (const loc of locales) {
    const c = bundle.locales[loc]
    if (!c) { score -= 20; issues.push(`missing locale ${loc}`); continue }
    if (/\[mock:/i.test(c.article)) { score -= 50; issues.push(`mock marker in ${loc} article`) }
    if ((c.article || '').trim().length < 400) { score -= 25; issues.push(`${loc} article too short`) }
    if ((c.faq || []).length < 3) { score -= 10; issues.push(`${loc} has <3 FAQs`) }
    if (!c.seo?.metaDescription) { score -= 10; issues.push(`${loc} missing meta description`) }
    if (!c.featuredSnippet) { score -= 5; issues.push(`${loc} missing featured snippet`) }
  }
  if (!bundle.faqSchema) { score -= 5; issues.push('missing FAQ schema') }

  score = Math.max(0, Math.min(100, score))
  return { score, pass: score >= THRESHOLD, issues }
}
