// ─────────────────────────────────────────────────────────────────
// lib/distribution/types.ts
// Shared types for the AI content distribution engine.
// ─────────────────────────────────────────────────────────────────

export type Locale = 'en' | 'hi'
export type Severity = 'low' | 'medium' | 'high' | 'critical'

/** The only input an operator must supply. */
export interface ScamInput {
  title: string
  description: string
  platform: string          // e.g. "WhatsApp", "UPI", "Telegram", "Email"
  region: string            // e.g. "India", "Maharashtra", "Global"
  severity: Severity
  /** Optional hints to steer generation. */
  sourceUrl?: string
  reporter?: string
}

export interface SeoMetadata {
  metaTitle: string
  metaDescription: string
  slug: string
  canonicalPath: string
  ogTitle: string
  ogDescription: string
  keywords: string[]
}

export interface GeoSummary {
  /** 1–2 sentence answer optimised for AI search / answer engines. */
  answer: string
  /** Bullet facts an LLM can lift verbatim. */
  keyFacts: string[]
  /** Entities & synonyms for retrieval. */
  entities: string[]
}

export interface SocialCopy {
  linkedin: string
  twitter: string          // X — single post, <= 280 chars
  twitterThread: string[]  // optional multi-tweet breakdown
  facebook: string
  threads: string
  reddit: { title: string; body: string; subreddits: string[] }
}

export interface ReelScript {
  hook: string
  beats: string[]          // 3–6 spoken beats / on-screen lines
  cta: string
  caption: string
  hashtags: string[]
  estimatedSeconds: number
}

export interface FaqItem {
  question: string
  answer: string
}

export interface InternalLink {
  anchor: string
  path: string
  reason: string
}

export interface LocalizedContent {
  locale: Locale
  article: string          // full markdown body
  seo: SeoMetadata
  geo: GeoSummary
  social: SocialCopy
  reel: ReelScript
  faq: FaqItem[]
  featuredSnippet: string  // ~40–55 word paragraph answer
  cta: string
  tags: string[]
  keywords: string[]
}

export interface ContentBundle {
  id: string
  input: ScamInput
  createdAt: number
  provider: string
  live: boolean            // false = generated by mock provider
  locales: Record<Locale, LocalizedContent>
  internalLinks: InternalLink[]
  relatedPages: InternalLink[]
  faqSchema: object        // JSON-LD FAQPage
  articleSchema: object    // JSON-LD Article / NewsArticle
}

export type ExportFormat = 'markdown' | 'html' | 'json'
