#!/usr/bin/env bash
# Auto-generated by gen-firestore-indexes.mjs — do not edit by hand.
# Creates Firestore vector indexes (KNN) via gcloud.
set -euo pipefail

gcloud firestore indexes composite create --collection-group=scam_reports --query-scope=COLLECTION --field-config=field-path=vector,vector-config='{"dimension":768,"flat":{}}'
gcloud firestore indexes composite create --collection-group=scam_clusters --query-scope=COLLECTION --field-config=field-path=centroid,vector-config='{"dimension":768,"flat":{}}'
gcloud firestore indexes composite create --collection-group=alerts --query-scope=COLLECTION --field-config=field-path=vector,vector-config='{"dimension":768,"flat":{}}'
